services:

  server:
    build:
      context: .
    environment:
      MS_PORT: ${MS_PORT}
      NODE_ENV: production
    ports: 
      - ${MS_PORT}:${MS_PORT} 
    volumes:
          - .:/usr/src/app
    depends_on:
      db:
        condition: service_healthy
      # redis:
      #   condition: service_healthy
  db:
    image: postgres:15.7
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=restaurant
      - POSTGRES_PASSWORD=postgres
    # expose:
      # - 5432 
    ports:
      - 5432:5432 
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  # redis:
  #   image: redis:6.2.3-alpine
  #   restart: unless-stopped
  #   ports:
  #     - 6379:6379

volumes:
  db-data:
